# brew tap Homebrew/bundle
# brew bundle

cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"

brew "openssl"
brew "sqlite"
brew "python"
brew "asciinema"
brew "bazel"
brew "binaryen"
brew "clang-format"
brew "cmake"
brew "colordiff"
brew "curl"
brew "direnv"
brew "fd"
brew "ffmpeg"
brew "git"
brew "git-lfs"
brew "go"
brew "graphviz"
brew "grpc"
brew "hub"
brew "imagemagick"
brew "jq"
brew "maven"
brew "mruby"
brew "peco"
brew "pipenv"
brew "poppler"
brew "qrencode"
brew "rbenv"
brew "redpen"
brew "sbt"
brew "the_silver_searcher"
brew "tree"
brew "watchman"
brew "wget"
brew "zsh"
brew "zsh-completions"
